apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
          claimName: redis-pvc
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: redis-api
            protocol: TCP
            containerPort: 6379
        volumeMounts:
          - name: redis-pvc
            mountPath: "/data"