apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
  namespace: redis
spec:
  serviceName: redis-slave
  replicas: 3
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:6.2
        command:
          - redis-server
        args:
          - "--slaveof"
          - "redis"
          - "6379"
        ports:
        - containerPort: 6379
          